### ISSUE TITLE
config as YAML

### ISSUE THREAD

**Issue by chb0github** [mybatis/migrations#90]
Hooks seem like a really cool and powerful feature. But the config syntax is a bit messy:

`hook_after_down=JavaScript:printvar.js:when=after:what=down`

would be much more inuitive as YAML:

```yaml
events:
  hook_after_down:
    hooks:
    - script: printvars.js
      type: javascript
      properties:
        when: after
        what: down
```

Also, declaring `JavaScript` is redundant if you go by convention: `.js` or Groovy as `.groovy`
